version: "3.9"
services:
  deven:
    container_name: deven
    build: 
      context: .
      dockerfile: deven-amazon-Dockerfile
    ports:
      - "${SSH_PORT:-22}:22"
    volumes:
      - deven-vol:/code
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  deven-vol:
    external: true