version: "3.9"
services:
  deven:
    container_name: deven
    build: 
      context: .
      dockerfile: deven-Dockerfile
    ports:
      - "${SSH_PORT:-22}:22"
    volumes:
      - deven-vol:/code
volumes:
  deven-vol:
    external: true