#!/bin/bash


echo "A"
# docker-compose --file $DEVEN_PATH/config/deven-docker-compose.yml up -d --build

# rm -f ~/.ssh/id_rsa
# echo "B"
# docker-compose --file $DEVEN_PATH/config/deven-docker-compose.yml exec -T -u deven deven bash -c 'cat ~/.ssh/id_rsa' > ~/.ssh/id_rsa
# chmod 400 ~/.ssh/id_rsa
# ssh-keygen -R 127.0.0.1

# if [[ -z "${SSH_PORT}" ]]; then

#     echo "To access this container use - 'ssh deven@127.0.0.1'"

# else

#     echo "To access this container use - 'ssh deven@127.0.0.1 -p ${SSH_PORT}'"

# fi
